Repository ivpn/android-app, pull requests merged in 2023-04, with the labels that each got.

#188 Screen shows bright white background on launch with dark mode
  core/src/main/res/values-night/styles.xml
  core/src/main/res/values/styles.xml
Labels: type: bug

#193 Servers change randomly when switching protocols
  core/src/main/java/net/ivpn/core/common/prefs/ServersPreference.kt
  core/src/main/java/net/ivpn/core/common/prefs/ServersRepository.kt
Labels: type: bug, OpenVPN, WireGuard

#196 Server.getIpAddresses NullPointerException
  core/src/main/java/net/ivpn/core/rest/data/model/Server.java
Labels: type: bug

#197 BillingManagerWrapper.initialPayment NullPointerException
  store/src/main/java/net/ivpn/client/billing/BillingManagerWrapper.java
Labels: type: bug

#204 AllServersRecyclerViewAdapter.onChangeState ArrayIndexOutOfBoundsException
  core/src/main/java/net/ivpn/core/v2/serverlist/all/AllServersRecyclerViewAdapter.kt
Labels: type: bug

#211 Connect to OpenVPN gateway using IP address
  core/src/main/java/de/blinkt/openvpn/core/Connection.java
Labels: OpenVPN, type: task

#214 Internet blocked when using OpenVPN + MultiHop + AnTitracker
  core/src/main/java/net/ivpn/core/common/prefs/EncryptedSettingsPreference.kt
  core/src/main/java/net/ivpn/core/common/prefs/ServersRepository.kt
  core/src/main/java/net/ivpn/core/common/prefs/Settings.kt
  core/src/main/java/net/ivpn/core/rest/data/model/AntiTracker.java
Labels: type: bug, OpenVPN

#229 Android 13 themed icon
  fdroid/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  fdroid/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  site/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  site/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  store/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  store/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: type: feature

#230 Add Accrescent to README.md
  README.md
Labels: type: documentation
